/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Entry {
  'id' : string,
  'dateCreated' : bigint,
  'name' : string,
  'paid' : boolean,
  'mobileNumber' : string,
  'commission' : bigint,
  'totalAmount' : bigint,
  'amount' : bigint,
  'advance' : bigint,
}
export interface HistoryEntry {
  'id' : string,
  'dateCreated' : bigint,
  'name' : string,
  'paid' : boolean,
  'mobileNumber' : string,
  'commission' : bigint,
  'totalAmount' : bigint,
  'amount' : bigint,
  'datePaid' : bigint,
  'advance' : bigint,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createEntry' : ActorMethod<[string, string, bigint, bigint, bigint], string>,
  'deleteEntry' : ActorMethod<[string], undefined>,
  'deleteHistoryEntry' : ActorMethod<[string], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getEntries' : ActorMethod<[], Array<Entry>>,
  'getHistoryEntries' : ActorMethod<[], Array<HistoryEntry>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'moveEntryToHistory' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateEntry' : ActorMethod<
    [string, string, string, bigint, bigint, boolean, bigint],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];